### ISSUE TITLE
Lint never connects to VS code

### ISSUE THREAD

**Issue by nxfi777** [aidenybai/million#1029]
### What version of `million` are you using?

0.0.73

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Firefox, Chrome

### Describe the Bug

I was originally using CRA, but the `craco` method does not resolve for the craco plugin object. I now am using the `webpack` method alongside `webpack-bundle-analyzer`. Here is my config:
```javascript
// craco.config.js
const BundleAanlyzerPlugin = require("webpack-bundle-analyzer").BundleAnalyzerPlugin;
const MillionCompiler = require('@million/lint');

module.exports = function () {
  return {
    webpack: {
      configure: {
        entry: './src/index.js',
      },
      plugins: [new BundleAanlyzerPlugin({ analyzerMode: "server" }), MillionCompiler.webpack()],
    },
  };
};
```

The million lint plugin is installed, and eslint is working correctly. The issue is that no matter how long I wait, or how much I play around with the site, million lint never connects to VS code in the dev server environment. The site is responsive, and I am using `block` for some static elements.

<img width="195" alt="Million lint" src="https://github.com/aidenybai/million/assets/127808926/7902af27-1a54-4b22-aed5-47e7b3010cc2">
<br></br>

![image](https://github.com/aidenybai/million/assets/127808926/0280eea3-5946-4a1d-8a62-2da0c81cb0e4)
 

### What's the expected result?

Million lint detects issues in my CSR SPA

### Link to Minimal Reproducible Example

--

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by sannajammeh** [comment]
Same issue here, it does not connect to VScode at all. Just shows the toolbar saying "connecting to vscode"

**Comment by roymrinmoy** [comment]
Facing the same issue here. Everything is same as the OP except I'm using Vite on mac.

**Comment by tobySolutions** [comment]
Hello there @nxfi777, @AhmedBaset, @sannajammeh, @roymrinmoy we have actually fixed this issue in the upcoming release and you will no longer experience this; apologies for the not so great first encounter.

**Comment by karthikmallireddy** [comment]
It's still not connecting.

**Comment by AhmedBaset** [comment]
> It's still not connecting.

Have you updated to `1.0.0-rc.1`?

**Comment by karthikmallireddy** [comment]
Yes but it's keep saying start dev server in VS Code.

**Comment by Stanzilla** [comment]
POST http://undefined:42423/ingest?z=1 net::ERR_NAME_NOT_RESOLVED

**Comment by Ic3m4n34** [comment]
same issue here

**Comment by ImLunaHey** [comment]
please stop replying with "same issue" if you dont have anything extra to add.

ive updated to `1.0.0-rc.1` and im using the webpack provider. still having issues.

@tobySolutions can you confirm which version this is meant to be fixed in?

**Comment by jessedubbink** [comment]
I have opened a question regarding the same issue this morning in the Discord server. Including the reproduction steps.


Hi, I'm excited to use Million Lint but I can't seem to login.

I've installed Million and MillionLint and installed the vscode extension. After which it guided me to authenticate using google or github. But after signing in with either of the options, it did not actually sign me in.

I'm still stuck on https://beta-million-lint.vercel.app/auth/callback in the browser.

I've tried using Arc and firefox but neither seem to solve the issue.

Steps:
1. I get the prompt to sign in, I click Allow.
2. I get the vscode confirmation to open the link to an external website, I click Open.
3. I sign in using GitHub
4. I get the authorization screen for Clerk, I click Authorize.
5. It tells me I'm redirected, after which I'm redirected to a blank page with the auth/callback url from above.

The plugin in vscode stays unauthenticated.

**Comment by ImLunaHey** [comment]
update. i managed to get an account made and the extension is now authenticated. i had to go through the login process a LOT of times though, finally on the last time it seems to have worked.

**Comment by aidenybai** [comment]
hey folks – we're working on it. merging the folks from #994 here

**Comment by NisargIO** [comment]
@Stanzilla 

> POST http://undefined:42423/ingest?z=1 net::ERR_NAME_NOT_RESOLVED

This should be fixed! Please update your npm package and try again

`npx @million/lint@latest`

**Comment by karthikmallireddy** [comment]
![Screenshot 2024-05-23 at 1 07 41 PM](https://github.com/aidenybai/million/assets/5372956/68422985-5d20-437f-9032-b7ea2e6f4fc1)
Updated to RC7 version and issue remains same it's a blank next js project Please find the attached screenshot.

**Comment by BrandonTing** [comment]
Updated to rc7 and I got different error message in console. It's a blank layout component using react router v6
 
<img width="1427" alt="截圖 2024-05-23 下午5 35 02" src="https://github.com/aidenybai/million/assets/53264454/125eac64-b8bd-4071-ba38-962f1d915dd6">

![截圖 2024-05-23 下午5 38 01](https://github.com/aidenybai/million/assets/53264454/55bac1c1-3065-4161-b1a7-d104e7c12485)

**Comment by aidenybai** [comment]
@karthikmallireddy 

We're not 100% sure why this is happening. We made the following changes:

- We listen on both `localhost` and `0.0.0.0`, previously just `localhost`
- We migrated from a file coordinating strategy to a server that holds the coordination map
- We have indicators to tell you which connection step you're on:

<img width="454" alt="image" src="https://github.com/aidenybai/million/assets/38025074/f7d69ed5-99fc-4700-ab9a-66b6bbd9a37c">

You can upgrade by installing the latest VSCode extension (v0.1.4) and upgrading Million Lint. This should help you upgrade:

```
npx million@latest
```

**Comment by ImLunaHey** [comment]
i've got a `webpack.config.ts` and get the following when running the above command.

```
 No build tool detected. No configuration file found in the current path: /Users/luna/code/axiomhq/app/frontend 
 ```

**Comment by nxfi777** [comment]
> i've got a `webpack.config.ts` and get the following when running the above command.
> 
> 
> 
> ```
> 
>  No build tool detected. No configuration file found in the current path: /Users/luna/code/axiomhq/app/frontend 
> 
>  ```

Separate issue, I suggest opening a new issue for this. Are you using craco? What framework are you using?

**Comment by ImLunaHey** [comment]
Are you using craco?
no

What framework are you using?
webpack + react

**Comment by karthikmallireddy** [comment]
> @karthikmallireddy
> 
> We're not 100% sure why this is happening. We made the following changes:
> 
> * We listen on both `localhost` and `0.0.0.0`, previously just `localhost`
> * We migrated from a file coordinating strategy to a server that holds the coordination map
> * We have indicators to tell you which connection step you're on:
> 
> <img alt="image" width="454" src="https://private-user-images.githubusercontent.com/38025074/333564535-f7d69ed5-99fc-4700-ab9a-66b6bbd9a37c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Nzg5MTYsIm5iZiI6MTcxNjU3ODYxNiwicGF0aCI6Ii8zODAyNTA3NC8zMzM1NjQ1MzUtZjdkNjllZDUtOTlmYy00NzAwLWFiOWEtNjZiNmJiZDlhMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE5MjMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZjBmODhiMjFhOTNjZWIwYzdkOGJmZDk2YzBiZTI5ZGJkNjI1OWUyMmM1OWVlNGZjYjE3YjVlNTQzYTBjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jucpfxKrjAbOEKhT3CIrVC4lirDCgeuWLG6at8QGCLI">
> You can upgrade by installing the latest VSCode extension (v0.1.4) and upgrading Million Lint. This should help you upgrade:
> 
> ```
> npx million@latest
> ```

@aidenybai  Thanks,After the new update it's now connected to visual studio code but react app is showing as not connected but core webvitals still showing as not connected despite dev mode is running in background.
![Screenshot 2024-05-24 at 6 17 15 PM](https://github.com/aidenybai/million/assets/5372956/5d4b157b-9982-4da1-8ce1-adab5303610f)

**Comment by BrandonTing** [comment]
It has worked on my project after upgrade to latest. Thanks for fixing.

**Comment by rburgst** [comment]
have a vite project with latest versions of million and million lint, I still see 
* ingest server: not connected
* react app: not connected

in the browser I see healthcheck XHRs being made as well as the browser console reports 
```
[Million Lint] Ingested 356 events 
```
Finally note that my react app is missing a few components after installing million lint (I did install million as well as I wasnt sure if it was needed or not). Also the installer reported an error and I did the vite configuration manually.

**Comment by QuiiBz** [comment]
If that can help, I had to remove `--turbo` from my `next dev` command to make it connect to the extension.

**Comment by imdavidkelly** [comment]
I have the same issue as @karthikmallireddy now

**Comment by lovincyrus** [comment]
After removing `--turbo` flag from `next dev`, it starts working. If the vscode extension is stuck on Ingest server and React app not connected, I'd reload the local development server.

```
> next dev

  ▲ Next.js 14.2.3
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...

 ⚡ Million Lint v1.0.0-rc.13
 - Local server: http://localhost:42423
```


My npm packages:
```
"@million/lint": "1.0.0-rc.13",
"million": "^3.1.6",
"next": "14.2.3",
"react": "^18",
"react-dom": "^18",
```

**Comment by roeku** [comment]
I don't have the --turbo flag, I get the million lint to ingest and can see Ingesting in my console but the VSCode plugin still does not work, I've tried with different projects but the plugin seems stuck, I installed previous version as well, disabled, uninstalled an reinstalled but get same results.
<img width="212" alt="image" src="https://github.com/aidenybai/million/assets/7256461/30bf3695-09fc-4e2c-b414-9040fc355052">
<img width="322" alt="image" src="https://github.com/aidenybai/million/assets/7256461/39169070-9142-4732-a191-6fb75e132dee">
<img width="429" alt="image" src="https://github.com/aidenybai/million/assets/7256461/82727892-d2b8-4766-80ac-d84aedef32e8">

I have installed using `npx million@latest`

My packages
`    
     "@million/lint": "^1.0.0-rc.18",
     "million": "^3.1.7",
     "react": "^18.2.0",
     "react-dom": "^18.2.0",
     "next": "^14.2.3",
`

I do have a somewhat complicated next.config.js

`const MillionLint = require('@million/lint');
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true'
});

const withPWA = require('@ducanh2912/next-pwa').default({
  dest: 'public',
  disable: process.env.NODE_ENV === 'development'
});
const nextConfig = {
  reactStrictMode: true,
  images: {
    remotePatterns: [{
      protocol: 'https',
      hostname: 'www.notion.so'
    }]
  },
  webpack(config, {
    isServer
  }) {
    if (!isServer) {
      config.externals.push('sharp');
    }
    config.module.rules.push({
      test: /\.(ogg|mp3|wav|mpe?g)$/i,
      exclude: config.exclude,
      use: [{
        loader: require.resolve('url-loader'),
        options: {
          limit: config.inlineImageLimit,
          fallback: require.resolve('file-loader'),
          publicPath: `${config.assetPrefix}/_next/static/images/`,
          outputPath: `${isServer ? '../' : ''}static/images/`,
          name: '[name]-[hash].[ext]',
          esModule: config.esModule || false
        }
      }]
    });

    // shader support
    config.module.rules.push({
      test: /\.(glsl|vs|fs|vert|frag)$/,
      exclude: /node_modules/,
      use: ['raw-loader', 'glslify-loader']
    });
    return config;
  },
  experimental: {
    nextScriptWorkers: true
  }
};
const KEYS_TO_OMIT = ['webpackDevMiddleware', 'configOrigin', 'target', 'analyticsId', 'webpack5', 'amp', 'assetPrefix'];
module.exports = (_phase, {
  defaultConfig
}) => {
  const plugins = [[withPWA], [withBundleAnalyzer, {}]];
  const wConfig = plugins.reduce((acc, [plugin, config]) => plugin({
    ...acc,
    ...config
  }), {
    ...defaultConfig,
    ...MillionLint.next({ rsc: true })(nextConfig)
  });
  const finalConfig = {};
  Object.keys(wConfig).forEach(key => {
    if (!KEYS_TO_OMIT.includes(key)) {
      finalConfig[key] = wConfig[key];
    }
  });
  return (finalConfig);
};`

**Comment by matej-kaska** [comment]
Having same problem. On the app I have bar with this text: Failed to connect. Is your VSCode window open?

Versions:
Extension: v0.1.8
milion: 3.1.7
milion/lint: 1.0.0-rc.18
VSCode: 1.89.1
Node: v20.10.0
Vite: 4.4.5
React: 18.2.0

I am stuck on Ingest server and React app - not connected

![image](https://github.com/aidenybai/million/assets/12019437/d7241b6e-70db-406c-a0cd-9dbaa0247089)

When I load the page I get some logs:

![image](https://github.com/aidenybai/million/assets/12019437/548a5aa5-0f8a-4db3-b180-5ce10f602955)

I tried to fiddle with some vite.config.ts settings, but it did not help:
```
import MillionLint from '@million/lint';
import million from 'million/compiler';
import react from "@vitejs/plugin-react-swc";
import { defineConfig } from "vite";
import sassGlobImports from "vite-plugin-sass-glob-import";
import svgr from "vite-plugin-svgr";
import tsconfigPaths from "vite-tsconfig-paths";

// https://vitejs.dev/config/
const _plugins = [react(), svgr(), tsconfigPaths(), sassGlobImports()];
_plugins.unshift(million.vite({
  auto: true
}), MillionLint.vite())
export default defineConfig({
  plugins: _plugins,
  server: {
    host: true,
    port: 3000,
    strictPort: true,
    watch: {
      usePolling: true
    },
    hmr: {
      clientPort: 3000,
      overlay: false
    }
  },
  define: {
    global: "window",
    "process.env.VITE_GITHUB_USERNAME": JSON.stringify(process.env.VITE_GITHUB_USERNAME)
  },
  build: {
    sourcemap: true,
    minify: "terser"
  },
  css: {
    postcss: "./postcss.config.js"
  },
  publicDir: "public"
});
```

Console:
![image](https://github.com/aidenybai/million/assets/12019437/cdf9b5a7-3290-4c74-a58f-14816530828c)

**Comment by afonsojramos** [comment]
Can confirm that the same is happening on a gatsby web app.
<img width="336" alt="image" src="https://github.com/aidenybai/million/assets/19473034/60626923-8fa7-4d40-b8d7-614a267d3988">
<img width="253" alt="image" src="https://github.com/aidenybai/million/assets/19473034/9437b927-0b6f-49c1-84bb-6d6d6d19556c">
Let me know if there is any additional info that you need to help you debug!

**Comment by AbbasPlusPlus** [comment]
> > @karthikmallireddy
> > We're not 100% sure why this is happening. We made the following changes:
> > 
> > * We listen on both `localhost` and `0.0.0.0`, previously just `localhost`
> > * We migrated from a file coordinating strategy to a server that holds the coordination map
> > * We have indicators to tell you which connection step you're on:
> > 
> > <img alt="image" width="454" src="https://private-user-images.githubusercontent.com/38025074/333564535-f7d69ed5-99fc-4700-ab9a-66b6bbd9a37c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Nzg5MTYsIm5iZiI6MTcxNjU3ODYxNiwicGF0aCI6Ii8zODAyNTA3NC8zMzM1NjQ1MzUtZjdkNjllZDUtOTlmYy00NzAwLWFiOWEtNjZiNmJiZDlhMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE5MjMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZjBmODhiMjFhOTNjZWIwYzdkOGJmZDk2YzBiZTI5ZGJkNjI1OWUyMmM1OWVlNGZjYjE3YjVlNTQzYTBjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jucpfxKrjAbOEKhT3CIrVC4lirDCgeuWLG6at8QGCLI">
> > You can upgrade by installing the latest VSCode extension (v0.1.4) and upgrading Million Lint. This should help you upgrade:
> > ```
> > npx million@latest
> > ```
> 
> @aidenybai Thanks,After the new update it's now connected to visual studio code but react app is showing as not connected but core webvitals still showing as not connected despite dev mode is running in background. ![Screenshot 2024-05-24 at 6 17 15 PM](https://private-user-images.githubusercontent.com/5372956/333711259-5d4b157b-9982-4da1-8ce1-adab5303610f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzE4NzgsIm5iZiI6MTcxOTU3MTU3OCwicGF0aCI6Ii81MzcyOTU2LzMzMzcxMTI1OS01ZDRiMTU3Yi05OTgyLTRkYTEtOGNlMS1hZGFiNTMwMzYxMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMTA0NjE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTc4NTU2NDI0MjQ5NGNkMzhlYmRjNWMwYTM4ZTIzM2JmMjBlZTRjMzg3YjcwNTliOGE1MGMyMTNhMGRkOGM3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.h2acMWjwHrfrjGiG9alUQZxR2cS7IcKMRp_HNg4vnFY)

I was having the same issue. I realized all I had to do was actually navigate to my application in the browser. Once I did this, the Million Lint VS Code extension started showing me performance info for the page I was viewing in my browser.

**Comment by MrgSub** [comment]
Removing `--turbo` worked for me

**Comment by absolutegravitas** [comment]
@MrgSub solution to remove --turbo also works for me although build times themselves are now super large (+15sec) for a small repo. Im using it as follows in combination withBundleAnalyzer on the Blazity/next-enterprise boilerplate repo

![Image](https://github.com/user-attachments/assets/f15d5bff-5548-46db-931a-995bf2461fcb)
