### ISSUE TITLE
Support for Ionic

### ISSUE THREAD

**Issue by Maxime-p** [aidenybai/million#1113]
### Describe the feature

Test and make Million lint work with Ionic

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Maxime-p** [comment]
I'm starting some tests and researchs and I having an error.

`IonTabs must contain an IonRouterOutlet`

It only happen when MillionLint.vite() is added in vite.config

**Comment by aidenybai** [comment]
Hi @Maxime-p, we've just deployed a fix for you. Can you try running the setup script npx million@latest. Once it's done, please restart your VSCode/Cursor. Let me know if that works for you!

**Comment by Maxime-p** [comment]
Hi,

Thank you for your response. I ran the setup script using npx million@latest and restarted VSCode several times, but unfortunately, I’m still encountering the same error and haven't noticed any changes.
![Capture d’écran 2024-10-02 à 13 53 56](https://github.com/user-attachments/assets/0efbad34-f23e-499e-b323-bc4de3678106)
