### ISSUE TITLE
NextJS client component issue (shadcn/ui)

### ISSUE THREAD

**Issue by ChrisBoik** [aidenybai/million#1123]
### What version of `million` are you using?

^1.0.0-rc.84

### Are you using an SSR adapter? If so, which one?

n/a local

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Chrome

### Describe the Bug

When using Million in NextJS with [shadcn/ui](https://ui.shadcn.com/), interactive use-client components (directly from [shadcn/ui - Dark Mode Toggle](https://ui.shadcn.com/docs/dark-mode/next#add-a-mode-toggle)) the interactive dropdown does not render on click toggle.

When I manually forced the dropdown to 'show' via props, although it does not visually appear, the dom now shows the dropdown elements but are translated off-screen.

Initially thought a shadcn/ui bug but turns out disabling Million solved this problem.
A user on Twitter seems to have experienced the same issue: [Twitter user's post](https://x.com/jonaylor89/status/1810471047369797899)

The button appears to basically lose all interactivity, the underlying shadcn/ui primitives do not even react to the click event as far as I can tell.

### What's the expected result?

My use-client components do not get affected by million's profiling/wrapper components (assumed).

### Link to Minimal Reproducible Example

Coming soon

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aidenybai** [comment]
Hi @ChrisBoik , we've just deployed a fix for you. Can you try running the setup script npx million@latest. Once it's done, please restart your VSCode/Cursor. Let me know if that works for you!

**Comment by Prains** [comment]
can confirm that on latest version on lint issue still persists

**Comment by sargon17** [comment]
same here, the issue persists on latest version

**Comment by manhtrv** [comment]
same here with the latest version

**Comment by hong-tm** [comment]
same here, break the shadcn chart component
