### ISSUE TITLE
bug: Found unsupported argument for block. Make sure blocks consume the reference to a component function, not the direct declaration.

### ISSUE THREAD

**Issue by J4v4Scr1pt** [aidenybai/million#417]
**Describe the bug**
First off, awesome work with this💪!!

Just installed million and trying to use the block as described in the [docs](https://million.dev/docs/quickstart#whats-a-block). But got the [warning ](https://million.dev/docs/rules#calling-block)for breaking the Rules of Block. Initially I tried to removed parts of my code  in the component that I thought could potentially affect this and none of it worked. I then removed my code for the component completely and replaced the whole component with code example show on the [github page](https://github.com/aidenybai/million#example-usage),  but still get the same warning.  I'm a bit lost on what could be wrong and how to solve the issue 🤔, help and a point to the right direction would be much appreciated.

**Expected behavior**
To work as expected.

**Screenshots**
![image](https://github.com/aidenybai/million/assets/5929055/adc39348-66e5-4d4e-82de-15a0f15cabee)

**Additional context**
package.js:
"million": "^2.4.6-beta.0",
"react": "^18.2.0",
"webpack": "^5.73.0",

**Comment by aidenybai** [comment]
Quick question – does this work during runtime? Is it just a warning?

**Comment by J4v4Scr1pt** [comment]
Yes sorry forgot to mention this, the warning accurs during build time. Runtime it does not give any warning or error and everything works.

![image](https://github.com/aidenybai/million/assets/5929055/80a4388c-b3d9-4cf3-a3d7-8d99c815e401)

**Comment by aidenybai** [comment]
Should be fixed in `v2.4.6-beta.1`!

**Comment by J4v4Scr1pt** [comment]
Wow that was a fast deploy 😁!

Installed it:
![image](https://github.com/aidenybai/million/assets/5929055/e23a1a53-c0ed-4d9d-9c77-81eda2896ce5)
But unfortunatly I still get the same issue 😢..

I will be away for a couple of hours now, but if there is **anything** I can provide I'm more than willing to help.
Just write here and I will get back to you as soon as I can!

You rock 🤘!

This is how the component looks:

```
import { useState } from "react";
import { block } from "million/react";

const Counter = block(function Counter({ initialCount }) {
	const [count, setCount] = useState(1);
	const handleClick = () => {
		setCount(count + 1);
	};
	return <button onClick={handleClick}>{count}</button>;
});

export default Counter;
```

**Comment by aidenybai** [comment]
Thank you! Sorry about that, just pushed another fix `v2.4.6-beta.2`. If that doesn't work, ping me again!

**Comment by ls-devs** [comment]
@aidenybai Hi, got the same error, posted on discord, I didn't saw this issue.
The error is still here even with `v2.4.6-beta.2`

**Comment by J4v4Scr1pt** [comment]
> Thank you! Sorry about that, just pushed another fix `v2.4.6-beta.2`. If that doesn't work, ping me again!

No need to be sorry mate! You do an awesome work with this! 😀
This solved the issue for me, now the error is gone 😄!

Keep the great work man! 🚀

**Comment by tobySolutions** [comment]
> > @aidenybai Hi, got the same error, posted on discord, I didn't saw this issue. The error is still here even with `v2.4.6-beta.2`
> 
> Have you tried doing a clean install of the npm packages? Because beta.2 solved this for me.. thinking

Hmm, interesting. What do you mean? I'm glad your issues have been resolved by the way!

**Comment by ls-devs** [comment]
The issue not gone for me even after clean install.
Maybe there's something to do with next.js ?

**Comment by aidenybai** [comment]
@ls-devs late, but can you share your usage?

**Comment by ls-devs** [comment]
> @ls-devs late, but can you share your usage?

Hi @aidenybai you already fixed it. I opened an issue on discord and u fixed it (pseudo discord : Despues)

**Comment by coy102** [comment]
Hi, I got an error when using vite, any idea?

![image](https://github.com/aidenybai/million/assets/13234170/78acbdd9-84d6-4154-a038-0a4bf3592ac0)

**Comment by tobySolutions** [comment]
> Hi, I got an error when using vite, any idea?
> 
> ![image](https://user-images.githubusercontent.com/13234170/248480327-78acbdd9-84d6-4154-a038-0a4bf3592ac0.png)

Hey! Can you share your code so we can reproduce this @coy102? We should probably close this issue for now.  Can you open another issue so we can track it?

**Comment by tobySolutions** [comment]
Thank you @J4v4Scr1pt, @aidenybai!

**Comment by coy102** [comment]
> > Hi, I got an error when using vite, any idea?
> > ![image](https://user-images.githubusercontent.com/13234170/248480327-78acbdd9-84d6-4154-a038-0a4bf3592ac0.png)
> 
> Hey! Can you share your code so we can reproduce this @coy102? We should probably close this issue for now. Can you open another issue so we can track it?

sure, i'll open another issue, thanks

**Comment by aidenybai** [comment]
@coy102 please open another issue, closing this
