### ISSUE TITLE
bug: million is dependant upon react

### ISSUE THREAD

**Issue by rayhanadev** [aidenybai/million#461]
**Describe the bug**
When using default Preact scaffolding and following the docs for Million with Preact I run into the following error:

```
failed to load config from /home/runner/FearfulLightRar/vite.config.ts
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'react' imported from /home/runner/FearfulLightRar/node_modules/million/dist/compiler.mjs
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

when using the `vite` command.

**To Reproduce**
1. `npm init preact`
3. Follow [this](https://million.dev/docs/install) guide to install Million with Preact & Vite
4. Run `vite`
5. See error

**Expected behavior**
I should not have to download `react` and `react-dom` when I am using pure Preact. The `react` library seems to get imported at the top level when Million is bundled on npm.

**Additional context**
Here's a link to the [Repl](https://replit.com/@RayAtReplit/FearfulLightRar) I used to make a minimal repro.

**Comment by rayhanadev** [comment]
The latest working version of Million for me is `2.4.2`, after `2.4.3` presumably `react` is being imported at the top level breaking things.

**Comment by aidenybai** [comment]
def looks like it should not be happening. either way, the preact version is out of sync with the react compat, so that needs to be fixed

**Comment by aidenybai** [comment]
Should be fixed in latest: https://unpkg.com/browse/million@2.4.9/dist/compiler.mjs

**Comment by rayhanadev** [comment]
@aidenybai it actually wasn't fixed: https://unpkg.com/browse/million@2.4.9/dist/preact.mjs
