### ISSUE TITLE
Error: the name `Component` is defined multiple times

### ISSUE THREAD

**Issue by vitaliy-grusha** [aidenybai/million#590]
### What version of `million` are you using?

2.6.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

Endless build using 2.6.0 with next@13.5.2. With million@v2.6.0-beta.16 works fine.
```
> next build


  ⚡ Million.js 2.6.0
  - Tip:     use // million-ignore for errors
  - Hotline: https://million.dev/hotline

⚡ <Component1> was ignored.
⚡ <Component2> was ignored.
⚡ <Component3> was ignored.
   Creating an optimized production build ..
``` 

### What's the expected result?

Build should not freeze.

### Link to Minimal Reproducible Example

- https://github.com/vitaliy-grusha/next-and-million

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aidenybai** [comment]
@vitaliy-grusha can you please provide more information and a basic reproduction?

**Comment by vitaliy-grusha** [comment]
@aidenybai The cause of this is a swc error. Here reproduction: https://github.com/vitaliy-grusha/next-and-million

The error:

```
> next build


  ⚡ Million.js 2.6.0
  - Tip:     use // million-ignore for errors
  - Hotline: https://million.dev/hotline

Failed to compile.

./src/components/Test.tsx
Error: 
  × the name `LoadingData` is defined multiple times
    ╭─[/Users/grushav/Documents/Projects/next-and-million/src/components/Test.tsx:2:1]
  2 │ 
  3 │ import { block as _block$ } from "million/react-server";
  4 │ import cls from '@/styles/Loader.module.scss';
  5 │ const LoadingData = ({
    ·       ─────┬─────
    ·            ╰── previous definition of `LoadingData` here
  6 │   small = false
  7 │ }: {
  8 │   small?: boolean;
  9 │ }) => {
 10 │   const sizeClass = small ? cls['loading_small'] : '';
 11 │   const titleClass = small ? 'text-sm' : 'text-2xl';
 12 │   const containerClass = small ? 'p-4' : 'p-6';
 13 │   const _ = `${containerClass} ${cls['loading-container']}`,
 14 │     _2 = `${cls['loading']} ${cls['loader']} ${sizeClass}`,
 15 │     _3 = `mx-0.5 bg-yellow ${cls['line']}`,
 16 │     _4 = `bg-light-blue ${cls['line']}`,
 17 │     _5 = `bg-primary ${cls['line']}`,
 18 │     _6 = `${titleClass} font-semibold`;
 19 │   return <P2iqihdjlsy5 _={_} _2={_2} _3={_3} _4={_4} _5={_5} _6={_6} />;
 20 │ };
 21 │ const P2iqihdjlsy5 = /*million:transform*/_block$(({
 22 │   _,
 23 │   _2,
 24 │   _3,
 25 │   _4,
 26 │   _5,
 27 │   _6
 28 │ }) => {
 29 │   return <div className={_}>
 30 │         <div className={_2}>
 31 │           <div className={_3}></div>
 32 │           <div className={_4}></div>
 33 │           <div className={_5}></div>
 34 │         </div>
 35 │         <h4 className={_6}>loading</h4>
 36 │       </div>;
 37 │ }, {
 38 │   svg: false,
 39 │   shouldUpdate: (a, b) => a?._ !== b?._ || a?._2 !== b?._2 || a?._3 !== b?._3 || a?._4 !== b?._4 || a?._5 !== b?._5 || a?._6 !== b?._6
 40 │ });
 41 │ const LoadingData = LoadingData;
    ·       ─────┬─────
    ·            ╰── `LoadingData` redefined here
 42 │ export default LoadingData;
    ╰────

Import trace for requested module:
./src/components/Test.tsx
./src/app/page.tsx


> Build failed because of webpack errors
   Creating an optimized production build . ELIFECYCLE  Command failed with exit code 1.
```

I thought that it was an endless build because, in a big project, gathering these errors takes so long.

**Comment by ps73** [comment]
For me this is reproducable with the empty vite react-ts starter template:
https://stackblitz.com/edit/vitejs-vite-nbdplm?file=vite.config.ts

**Comment by tobySolutions** [comment]
Hmm, does this issue still occur for you both? I'm gonna try to reproduce this.

**Comment by nnennajohn** [comment]
I can confirm that this happens with 2.6.0. Uninstalled and installed v2.6.0-beta.16 and the error goes away.

**Comment by raiyansarker** [comment]
It is also happening to me!

**Comment by officialanurag** [comment]
It's happening to me too!

**Comment by acorn1010** [comment]
I'm getting this error too when I define my functional components using function syntax instead of `const` syntax:

```typescript
// Errors out with a line: const SiteTheme = SiteTheme;
export function SiteTheme(props: React.PropsWithChildren<{children?: React.ReactNode}>) { ... }

// No error
export const SiteTheme = (props: React.PropsWithChildren<{children?: React.ReactNode}>) => { ... }
```

**Comment by ps73** [comment]
> I can confirm that this happens with 2.6.0. Uninstalled and installed v2.6.0-beta.16 and the error goes away.

This is the case for me too.

**Comment by aidenybai** [comment]
@ps73 @acorn1010 @officialanurag @raiyansarker @nnennajohn @vitaly-grusha Fixed on v2.6.1. Please run `npm i million@latest` to upgrade

**Comment by nnennajohn** [comment]
Great. Thank you.

> @ps73 @acorn1010 @officialanurag @raiyansarker @nnennajohn @vitaly-grusha Fixed on v2.6.1. Please run `npm i million@latest` to upgrade

**Comment by vitaliy-grusha** [comment]
I still can’t build the main project with million@v2.6.1. It just gets stuck on 'Creating an optimized production build...'. It still works fine with million@v2.6.0-beta.16. However, my reproduction repo builds normally with million@v2.6.1. This might be a different issue, but I have no idea how to debug it, or reproduce

**Comment by ps73** [comment]
> @ps73 @acorn1010 @officialanurag @raiyansarker @nnennajohn @vitaly-grusha Fixed on v2.6.1. Please run `npm i million@latest` to upgrade

Thanks a lot. It works now for me! 👍

**Comment by aidenybai** [comment]
Fixed @vitaliy-grusha, can you try again on v2.6.2?

**Comment by SalahAdDin** [comment]
It still has an erratic behaviour with **NextJS 13**.

**Comment by vitaliy-grusha** [comment]
@aidenybai Unfortunately, the issue persists; it still freezes during the build process. However, I've to create a reproduction: https://stackblitz.com/edit/nextjs-wend2n-million

You can run `npm run build` to observe the freezing issue.

I've traced the root of the freezing to a conditional return in the `Test.tsx` component:

```tsx
  if (isLoading) { // << this condition causes the build to freeze
    return (
      <>
        <div className={`${containerClass} ${cls['loading-container']}`}>
          <div
            className={`${cls['loading']} ${cls['loader']} ${sizeClass}`}
          ></div>
          <pre>{google ?? 'loading'}</pre>
          <h4 className={`${titleClass} font-semibold`}>{'loading'}</h4>
        </div>
      </>
    );
  }

  return (
    <div>
      <pre>{google ?? "loading"}</pre>
    </div>
  );
```

Eliminating the if (isLoading) block allows the build to complete successfully.

**Comment by aidenybai** [comment]
@salahaddin @vitaliy-grusha can you try again on latest?

**Comment by vitaliy-grusha** [comment]
@aidenybai Same behavior. Tested with million@2.6.3: https://stackblitz.com/edit/nextjs-wend2n-million

**Comment by vitaliy-grusha** [comment]
@aidenybai i will try. Seems million@2.6.4 not released on npm yet

**Comment by aidenybai** [comment]
Should be released now @vitaliy-grusha

**Comment by SalahAdDin** [comment]
> @vitaliy-grusha latest should fixed. i tested all use cases and no more infinite recursion? hopefully. let me know if it breaks

is it worthy to be used in a project whit only two client components? :')

**Comment by vitaliy-grusha** [comment]
@aidenybai, it works! Thank you!
